### ISSUE TITLE
JSON response

### ISSUE THREAD

**Issue by eatyourpeas** [wardle/uk-deprivation#2]
I hope you don't mind more questions from me through here
I have deprivare working locally - accessible via postman and getting sensible responses. 
I am not sure the response object I get back though is JSON though - is there a way that it could be?
I am looking to run deprivare as a service for an API of my own, and consume it using the standard python request library.
Do I have this right?
If so, is there any appetite to tweak the response from calls to deprivare to be in JSON?

**Comment by wardle** [comment]
The default is edn, but you can specify the format you want in your request header. Try application/json 

I could change the default, as JSON is probably a more reasonable default, but its usually better to be specify in the content type you're requesting from a service anyway!

**Comment by wardle** [comment]
Server implementation now returns JSON by default. Fixed in 4f9583cc2ebcdcda61f2658fd64516862f949d6e

**Comment by eatyourpeas** [comment]
thank you :)
